name: wagazap

services:
  app:
    image: agenciaboz/wagazap
    container_name: wagazap
    ports:
      - "8084:8084"
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 256M

networks:
  default:
    name: wagazap_network